# This file is a template, and might need editing before it works on your project.
# use docker image with latex preinstalled
# since there is no official latex image, use https://github.com/blang/latex-docker
# possible alternative: https://github.com/natlownes/docker-latex
image: ashwinvis/latex-pandoc-python

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .cache/pip
    - venv/

build:
  before_script:
    - tlmgr update --self
    - tlmgr install texliveonfly
        type1cm braket
        glossaries datatool xfor textcase xkeyval mfirstuc substr fp
        ccicons
        # biblatex biber xcolor lineno etoolbox fvextra fancyvrb
        # upquote ifplatform xstring framed caption outlines booktabs enumitem
        # babel-swedish microtype csquotes logreq setspace
    - texhash
    - updmap-sys --enable Map=ccicons.map
    - python -m venv venv
    - source venv/bin/activate
    - pip install -r requirements.txt
  script:
    - make -j
  artifacts:
    paths:
      - "*.pdf"
